main: dev.zontreck.amp.AutoMoneyPlugin
name: AutoMoneyPlugin
version: "1.0.032125.0058"
api-version: "1.21.1"
author: zontreck
description: A simple plugin providing automatic money to online players.
commands:
permissions: