main: dev.zontreck.amp.AutoMoneyPlugin
name: AutoMoneyPlugin
version: "1.0.081425.0939"
api-version: "1.21.8"
author: zontreck
description: A simple plugin providing automatic money to online players.
commands:
permissions:
